juwonpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    # None
    path('', views.IndexView, name='index'),
    
    path('orderdetail/<int:order_id>/', views.OrderDetailView, name='order_detail'),
    path('productdetail/<int:product_id>/', views.ProductDetailView, name='product_detail'),
    
    path('removeproduct/<int:d_product_id>/', views.RemoveProductView, name='remove_product'),
    path('removeorder/<int:d_order_id>/', views.RemoveOrderView, name='remove_order'),
    
    path('dashboard/', views.DashboardView, name='dashboard'),
    path('about/', views.AboutView, name='about'),
    path('product/', views.ProductView, name='product'),
]

mainapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	name = models.CharField(max_length=15, default="")
	image = models.ImageField(upload_to="images/")
	descrp = models.TextField()
	pub_date = models.DateTimeField("date published")
	
	def __str__(self):
		return self.name
		
		
class Order(models.Model):
	product_id = models.CharField(max_length=15, default="") #, on_delete=models.CASCADE)
	quantity = models.CharField(max_length=15, default="")
	name_owner = models.CharField(max_length=35, default="")
	phone_owner = models.CharField(max_length=15, default="")
	email_owner = models.EmailField()
	comment = models.TextField()
	pub_date = models.DateTimeField("date published")
	
	def __str__(self):
		return self.name_owner
		
		

mainapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from datetime import date
from django.utils import timezone
from .models import Order, Product
# Create your views here.

def IndexView(request):

	products = Product.objects.order_by("-pub_date")
	
	context = {"products": products}
	return render(request, "mainapp/index.html", context)
	
def AboutView(request):
	context = {}
	return render(request, "mainapp/about.html", context)
	

def DashboardView(request):
	if request.method == "POST":
		name = request.POST.get("name")
		pub_date = timezone.now()
		image = request.FILES["image"]
		descrp = request.POST.get("descrp")
		
		product = Product.objects.create(name=name, image=image, descrp=descrp, pub_date=pub_date)
		product.save()
		return HttpResponseRedirect(reverse("mainapp:dashboard"))
		
	else:
		orders = Order.objects.order_by('-pub_date')
		products = Product.objects.order_by("-pub_date")
	
		context = {"orders": orders, "products": products}
		return render(request, "mainapp/dashboard.html", context)
	
def OrderDetailView(request, order_id):
	order = get_object_or_404(Order, pk=order_id)
	product = get_object_or_404(Product, pk=order.product_id)
	context = {"order": order, "product": product}
	return render(request, "mainapp/order_detail.html", context)
	
def ProductDetailView(request, product_id):
	
	if request.method == "POST":
		quantity = request.POST.get("quantity")
		pub_date = timezone.now()
		comment = request.POST.get("comment")
		phone_owner = request.POST.get("phone_owner")
		email_owner = request.POST.get("email_owner")
		name_owner = request.POST.get("name_owner")
		
		
		order = Order.objects.create(product_id=product_id, quantity=quantity, name_owner=name_owner, phone_owner=phone_owner, email_owner=email_owner, comment=comment, pub_date=pub_date)
		
		order.save()
		return HttpResponseRedirect(reverse("mainapp:index"))
	
	else:
		product = get_object_or_404(Product, pk=product_id)
		context = {"product": product}
		return render(request, "mainapp/product_detail.html", context)
	

def ProductView(request):
	context = {}
	return render(request, "mainapp/product.html", context)
	
def RemoveProductView(request, d_product_id):
	Product.objects.filter(pk=d_product_id).delete()
	Order.objects.filter(product_id=d_product_id).delete()
	return HttpResponseRedirect(reverse("mainapp:dashboard"))
	#if request.method == "POST":

	#else:
	#	return render(request, "mainapp/delete_product.html")
	#return HttpResponse("asdfg")
	#if request.method == "GET":
	#product = get_object_or_404(Product, pk=product_id)
	
	
def RemoveOrderView(request, d_order_id):
	Order.objects.filter(pk=d_order_id).delete()
	return HttpResponseRedirect(reverse("mainapp:dashboard"))
	

mainapp/templates/mainapp/about.html
{% extends "mainapp/base.html" %}

{% block title %}
	AboutPage
{% endblock %}

{% block content %}
	<p>about page</p>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

    <title>{% block title %}{% endblock %}</title>




	{% block content %}
	{% endblock %}

mainapp/templates/mainapp/dashboard.html
{% extends "mainapp/base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}
	<p>dashboard</p>
	<br />
	<h3>all orders</h3>
	<ul>
		{% for order in orders %}
			<li>
				<a href="{% url 'mainapp:order_detail' order.id %}" />{{ order }}</a>  | 
				<a href="{% url 'mainapp:remove_order' order.id %}" />delete</a>
			</li>
		{% endfor %}
	</ul>
	
	<br />
	<h3>Add Product</h3>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
            <input  type="text"  name="name" placeholder="name"><br />
            <input type="file" name="image" accept="image/*"><br />
            <textarea name="descrp" rows="5" placeholder="Enter the descrp"></textarea><br />
           <button class="bttn bttn-primary">Submit!</button>
        </form>
        
   	<br />
	<h3>all products</h3>
	<ul>
		{% for product in products %}
			<li>{{ product }} | 
			<a href="{% url 'mainapp:remove_product' product.id %}" />delete</a>
			</li> 
		{% endfor %}
	</ul>
	
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}
 

{% block title %}
	Index Page
{% endblock %}

{% block content %}

<p>Welcome to index</p>
	
	<h3>all products</h3>
	
	<ul>
		{% for product in products %}
			<li><a href="{% url 'mainapp:product_detail' product.id %}" />{{ product }}</a></li>
		{% endfor %}
	</ul>



{% endblock %}

mainapp/templates/mainapp/order_detail.html
{% extends "mainapp/base.html" %}

{% block title %}
	Detail Page
{% endblock %}

{% block content %}
	<p>detail page</p>
	
	<p>
		product detail<br />
		{{ product.name }}<br />
		{{ product.descrp }}<br />
		{{ product.pub_date }}<br />
	</p>
	
	<p>
		order detail<br />
		{{ order.quantity }}<br />
		{{ order.name_owner }}<br />
		{{ order.phone_owner }}<br />
		{{ order.email_owner }}<br />
		{{ order.comment }}<br />
		{{ order.pub_date }}<br />
	</p>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends "mainapp/base.html" %}

{% block title %}
	Product Page
{% endblock %}

{% block content %}
	<p>product page</p>
{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends "mainapp/base.html" %}

{% block title %}
	Product Detail Page
{% endblock %}

{% block content %}
	<p>Product detail page</p>
	
	{{ product.name }}<br />
	{{ product.descrp }}<br />
	<img src="{{ product.image.url }}"  width="75px" height="90px" />
	{{ product.pub_date }}<br />
	
	
	<br />
	<h3>Make Order</h3>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input  type="text"  name="quantity" placeholder="quantity"><br />
            <input  type="text"  name="name_owner" placeholder="your name"><br />
            <input  type="text"  name="phone_owner" placeholder="your phone"><br />
            <input  type="email"  name="email_owner" placeholder="your email"><br />
            <textarea name="comment" rows="5" placeholder="Enter the comment"></textarea><br />
           <button class="bttn bttn-primary">Submit!</button>
        </form>
{% endblock %}